default_twitter: &default_twitter
  twitter_api_key: 'OmCCaS8IeNF2QBp7dT8jFVjOg'
  twitter_api_secret_key: 'hbizoP8UDmiTcOWc4RKSnYCmzqh9MA9VWHb9drv4eeep0sebB1'

development:
  secret_key_base: 1da2771a12d411664a8a8abce5980c4b6f4bf1587753f1d0d75aadbdeb1a1ba764bb142e904b3b29ee4a72c90c466daa857746caed82789c730f48862cdd3ce9
  <<: *default_twitter

test:
  secret_key_base: f8872c4552cc4ee88d949910b637e01efbc5320cc47d722c5a2471b9ff0515f051e542bf064e4a3a8ae0acd403f61d75c9b803c202c12d1c58bef8211da205b1
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *default_twitter
